# Generated by Django 5.2.7 on 2025-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.CharField(blank=True, default='ГБОУ 444', max_length=255, verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, default='ГБОУ 444', max_length=255, verbose_name='Школа'),
        ),
    ]
