# Generated by Django 5.2.7 on 2025-11-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_achievement_moderated_at_achievement_moderated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='moderated_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='status',
        ),
        migrations.DeleteModel(
            name='TeacherStudentRelationship',
        ),
    ]
