# Generated by Django 5.2.7 on 2025-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_achievement_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher_status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
